### ISSUE TITLE
bug: snapshot/revertTo causes tests to pass unexpectedly

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3055]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (48d5d79 2022-09-01T00:10:22.933552Z)

### What command(s) is the bug in?

forge test

### Describe the bug

If you run this test, it passes. If you comment out the `vm.revertTo` line it fails. Failure is expected in both cases since the assertion should fail. It seems like the cause is that reverting the state also reverts the `failed` flag: https://github.com/dapphub/ds-test/blob/9310e879db8ba3ea6d5c6489a579118fd264a3f5/src/test.sol#L47-L63
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;
import "forge-std/Test.sol";

contract MyTest is Test {
  function test_snapshot() external {
    uint256 snapId = vm.snapshot();
    assertEq(uint256(0), uint256(1));
    vm.revertTo(snapId);
  }
}
```

**Comment by mattsse** [comment]
>  It seems like the cause is that reverting the state also reverts the failed flag:

that sounds right, need to make a check for `failed()` here

**Comment by mattsse** [comment]
with #3087 this now results in

```console
~/git/rust/foundry/target/debug/forge test                                                                                                           ! master 
[⠢] Compiling...
No files changed, compilation skipped

Running 1 test for test/Counter.t.sol:MyTest
[FAIL. Reason: Assertion failed.] test_snapshot() (gas: 15534)
Test result: FAILED. 0 passed; 1 failed; finished in 2.71ms

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:MyTest
[FAIL. Reason: Assertion failed.] test_snapshot() (gas: 15534)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by graykode** [comment]
This still doesn't work. But after modifying a few lines in forge-std, it works. https://github.com/foundry-rs/forge-std/pull/241 @mattsse

**Comment by mds1** [comment]
@mattsse I was able to reproduce the issue from @graykode, any idea on the cause?

The forge-std fix in https://github.com/foundry-rs/forge-std/pull/241 does resolve the issue, but I'm not sure why. Regardless though, seems this should be fixed upstream here in foundry instead?

**Comment by mattsse** [comment]
looks strange, I have to take a closer look

**Comment by ZeroEkkusu** [comment]
@mattsse, see https://github.com/foundry-rs/forge-std/pull/241#pullrequestreview-1197652188.

**Comment by xenoliss** [comment]
Hey ! I'm still facing this issue on forge std `c7d30303fc34b7b2a680c86ddc1cd186bec23614`. Here is a PoC code:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract TestMe is Test {
    function testMe() public {
        uint256 snapshot = vm.snapshot();
        assertTrue(false);

        vm.revertTo(snapshot);
        assertTrue(true);
    }
}
```
This outputs the following:
```
$ forge test --match-test testMe -vv
[⠒] Compiling...
No files changed, compilation skipped

Running 1 test for test/TestMe.t.sol:TestMe
[PASS] testMe() (gas: 11436)
Logs:
  Error: Assertion Failed
```

The only was to view the failing test is using a more verbose mode like `-vv`, else this is totally invisible.
Also when nesting snapshots, the logs are simply vanished and `--vv` does not log the errors.

**Comment by OliverNChalk** [comment]
For those facing this issue, you may wish to use the following as a temp workaround:
```solidity

    function _revertTo(uint256 aSnapshot) private {
        require(!failed(), "Fail flag triggered, aborting revert");

        vm.revertTo(aSnapshot);
    }
```

**Comment by mattsse** [comment]
hmm, I'm not quite sure what the issue is here, because both examples fail.

or is the problem that the first assertion doesn't stop execution?

this behavior has ds-test legacy reasons but I'm skeptical that this is any good...

**Comment by OliverNChalk** [comment]
Interesting, I can get logged test failures without the test failing:
![image](https://user-images.githubusercontent.com/11343499/229199976-94333834-571c-4d44-8c02-fa44860170aa.png)

I am on a fork while using `vm.revertTo`. My forge version is `forge 0.2.0 (0f1dea4 2023-03-31T00:07:29.356304995Z)`. Let me try get you a repro a bit later

**Comment by OliverNChalk** [comment]
@mattsse It appears that fuzz testing breaks whatever code was introduced to persist the failure state. That said, I vaguely remember seeing this fail prior to fuzzing. However, perhaps they share the same root cause.

This minimal repro should make it easier to track down:
https://github.com/OliverNChalk/revert-to-repro

**Comment by mattsse** [comment]
thanks, will check!
