### ISSUE TITLE
Bug: `backend: failed while inspecting: Transaction(CreateInitcodeSizeLimit))`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5088]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5c2741 2023-05-31T00:03:46.340876004Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

For repro, use my repo [here](https://github.com/pcaversaccio/snekmate/tree/vyper-039) with the `vyper-039` branch and simply run `forge test`.

I upgraded my test setup using solc `0.8.20` and `evm_version='shanghai'`. However, I get multiple errors like the following if I run `forge test` (see here a CI run example: https://github.com/pcaversaccio/snekmate/actions/runs/5132149269/jobs/9233075709#step:11:44)

```bash
2023-05-31T11:14:59.396656Z ERROR forge::multi_runner: error=Unrecoverable error: Err(Eyre(
backend: failed while inspecting: Transaction(CreateInitcodeSizeLimit)))
```

I'm fully aware of the init code size limit introduced by `shanghai` but I'm not sure about this error and its impact. It seems that the tests are running successfully but instead of lasting now (around 25-30mins; see e.g. https://github.com/pcaversaccio/snekmate/actions/runs/5126407871/jobs/9220852266#step:11:1), they are completed within 7-10 mins (see e.g. https://github.com/pcaversaccio/snekmate/actions/runs/5132149269/jobs/9233075709#step:11:1)

![image](https://github.com/foundry-rs/foundry/assets/25297591/ae51d80e-851f-412d-b6d1-fe1ab5b404a1)
![image](https://github.com/foundry-rs/foundry/assets/25297591/12085e54-b49e-43c2-85ff-8a789246b2e5)

I can't explain the performance boost tbh. This smells like something is wrong (except ofc if Foundry, ethers-rs or any other major dependency was significantly refactored).

**Comment by DaniPopes** [comment]
The error here is that forge is failing to deploy the test contract itself (or a required library) because it's too big after the Shanghai changes.

Error is here:
https://github.com/foundry-rs/foundry/blob/a5c27411c7e5d1dd574df758060da8ad501ecbde/forge/src/runner.rs#L143

cc @mattsse @Evalir

**Comment by pcaversaccio** [comment]
hmm interesting, that `shanghai` upgrade creates a lot of issues lol. Not sure what I should do now since I need to test my Vyper contracts with the latest `0.3.9` release and Vyper defaults to `shanghai`. Also, any idea about the performance boost? Is it because deployments are skipped as you mentioned?

**Comment by DaniPopes** [comment]
> Is it because deployments are skipped as you mentioned?

Yes. I'm not sure why only execution errors fail the tests, while anything else just gets logged and ignored..

**Comment by mattsse** [comment]
... sigh, this is bad -.-

however https://github.com/bluealloy/revm/pull/491 should fix that, but we don't have it in foundry yet

I believe https://github.com/foundry-rs/foundry/pull/5089 should do it, mind trying this?

separately @Evalir we should treat this as test failures

**Comment by pcaversaccio** [comment]
Can confirm that with https://github.com/foundry-rs/foundry/releases/tag/nightly-b0c95d0151efa536931d0fc9d3950adb081ea866 it fails now. When is https://github.com/bluealloy/revm/pull/491 added? My PR here https://github.com/pcaversaccio/snekmate/pull/122 needs the `shanghai` version and can't revert back (since need to test Vyper's default behaviour which is `shanghai` since version `0.3.8`).

**Comment by mattsse** [comment]
should be included, 
what's the error now?

for testing, the contract code size limit should be disabled

**Comment by pcaversaccio** [comment]
Sorry I didn't use the latest `forge` version for testing. Seems to work (the CI is still running here: https://github.com/pcaversaccio/snekmate/actions/runs/5135950150/jobs/9242037892#step:11:18).

I mean I still get the warnings since my contracts are even bigger than 2x the init code limit. Maybe you consider bumping the threshold even higher for testing.

```bash
Warning (3860): Contract initcode size is 90430 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> test/extensions/ERC4626.t.sol:13:1:
   |
13 | contract ERC4626VaultTest is ERC4626Test {
   | ^ (Relevant source part starts here and spans across multiple lines).
Warning (3860): Contract initcode size is 140508 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> test/tokens/ERC1155.t.sol:17:1:
   |
17 | contract ERC1155Test is Test {
   | ^ (Relevant source part starts here and spans across multiple lines).
Warning (3860): Contract initcode size is 77723 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
 --> test/tokens/ERC[20](https://github.com/pcaversaccio/snekmate/actions/runs/5135950150/jobs/9242037892#step:11:21).t.sol:9:1:
  |
9 | contract ERC20Test is Test {
  | ^ (Relevant source part starts here and spans across multiple lines).
Warning (3860): Contract initcode size is 102289 bytes and exceeds 49152 bytes (a limit introduced in Shanghai). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> test/tokens/ERC721.t.sol:20:1:
   |
20 | contract ERC7[21](https://github.com/pcaversaccio/snekmate/actions/runs/5135950150/jobs/9242037892#step:11:22)Test is Test {
   | ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by mattsse** [comment]
cool, looks like we need to suppress the error now.

on it!

**Comment by pcaversaccio** [comment]
Completed via https://github.com/foundry-rs/foundry/pull/5094.

**Comment by mattsse** [comment]
nice, thanks for flagging
